### ISSUE TITLE
Unable to connect MQTTS, with some type of certificates

### ISSUE THREAD

**Issue by haydockjp** [hybridgroup/cylon-mqtt#9]
> Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)

Either my certificate or my install of my certificate is not 100% good enough for this connect. mqtt will allow you to connect and ignore this issue, but the option is not checked for.

Would you consider adding this code to the adapter?
`  if (opts.rejectUnauthorized != undefined) {
    this.additionalOpts.rejectUnauthorized = opts.rejectUnauthorized;
  }
`

**Comment by deadprogram** [comment]
Hi @haydockjp sounds a little like you are missing an intermediate certificate. In any case, a PR with that option sounds reasonable as well, and would be appreciated.

**Comment by haydockjp** [comment]
I am not sure if you meant for me to do this, but I submitted a pull request to do it. First time I have tried to pull request into someone else Git repo. Let me know if this is what you wanted, and if it worked.

Thanks
